package top.pkumc.trustedbridgeauth;

import org.slf4j.LoggerFactory;

import java.io.*;
import java.net.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;

import javax.net.ssl.SSLSocket;

/** Runs against synthetic credentials generated by provision-tls.py. */
public final class BridgeLinkTest {
    static int checks;

    static void require(boolean value, String message) {
        checks++;
        if (!value) throw new AssertionError(message);
    }

    static void await(java.util.function.BooleanSupplier condition) throws Exception {
        long end = System.nanoTime() + TimeUnit.SECONDS.toNanos(20);
        while (!condition.getAsBoolean()) {
            if (System.nanoTime() > end) throw new AssertionError("Timeout");
            Thread.sleep(25);
        }
    }

    static BridgeConfig config(Path keys, boolean server, int port, byte[] secret) {
        return new BridgeConfig(
                server ? "pkumc" : "thunion",
                server ? "thunion" : "pkumc",
                "127.0.0.1",
                port,
                server ? "listen" : "connect",
                "127.0.0.1",
                25565,
                "127.0.0.1",
                1500,
                30000,
                secret,
                "source",
                Map.of(),
                keys);
    }

    public static void main(String[] args) throws Exception {
        Path keys = Path.of(args[0]);
        byte[] secret = new byte[32];
        new java.security.SecureRandom().nextBytes(secret);
        int port;
        try (ServerSocket free = new ServerSocket(0)) {
            port = free.getLocalPort();
        }
        AtomicInteger received = new AtomicInteger();
        AtomicBoolean rejectNext = new AtomicBoolean();
        AtomicBoolean corruptAck = new AtomicBoolean();
        BridgeLink.Receiver handler =
                frame -> {
                    if (rejectNext.getAndSet(false)) throw new IOException("Policy rejection");
                    received.incrementAndGet();
                    if (corruptAck.getAndSet(false)) return new byte[HandoffProtocol.MAC_LENGTH];
                    return HandoffProtocol.acknowledgement(frame, secret);
                };
        var log = LoggerFactory.getLogger("BridgeLinkTest");
        BridgeConfig serverConfig = config(keys.resolve("pkumc"), true, port, secret);
        BridgeConfig clientConfig = config(keys.resolve("thunion"), false, port, secret);
        BridgeLink server = new BridgeLink(serverConfig, handler, log);
        try (BridgeLink client = new BridgeLink(clientConfig, handler, log)) {
            server.start();
            // The listener pins the distinct client identity.
            try (BridgeLink wrong =
                    new BridgeLink(
                            config(keys.resolve("pkumc"), false, port, secret), handler, log)) {
                wrong.start();
                Thread.sleep(2000);
                require(!server.connected() && !wrong.connected(), "wrong certificate rejected");
            }
            client.start();
            await(() -> client.connected());
            BridgeLink current = server;
            await(current::connected);
            HandoffProtocol.Frame frame =
                    new HandoffProtocol.Frame(new byte[] {1, 2, 3}, new byte[32]);
            try (ExecutorService jobs = Executors.newFixedThreadPool(8)) {
                List<Future<?>> results = new ArrayList<>();
                for (int i = 0; i < 24; i++) {
                    BridgeLink target = i % 2 == 0 ? server : client;
                    results.add(
                            jobs.submit(
                                    () -> {
                                        try {
                                            target.send(frame);
                                        } catch (IOException e) {
                                            throw new UncheckedIOException(e);
                                        }
                                    }));
                }
                for (Future<?> result : results) result.get(10, TimeUnit.SECONDS);
            }
            require(received.get() == 24, "concurrent bidirectional ACK correlation");
            rejectNext.set(true);
            try {
                client.send(frame);
                throw new AssertionError("Rejected handoff accepted");
            } catch (IOException expected) {
                require(expected.getMessage().equals("Peer rejected handoff"), "rejection preserves cause");
            }
            require(client.connected() && server.connected(), "policy rejection preserves shared connection");
            try {
                client.send(new HandoffProtocol.Frame(new byte[HandoffProtocol.MAX_FRAME_SIZE + 1], new byte[32]));
                throw new AssertionError("Oversized outbound frame accepted");
            } catch (IOException expected) {
                require(client.connected(), "local invalid frame does not damage link");
            }
            server.close();
            await(() -> !client.connected());
            try {
                client.send(frame);
                throw new AssertionError("Disconnected send accepted");
            } catch (IOException expected) {
                checks++;
            }
            server = new BridgeLink(serverConfig, handler, log);
            server.start();
            await(client::connected);
            BridgeLink restarted = server;
            await(restarted::connected);
            client.send(frame);
            server.send(frame);
            require(received.get() == 26, "automatic reconnect restores both directions");
            Thread.sleep(16000);
            require(
                    server.connected() && client.connected(),
                    "heartbeats keep idle connection alive");
            try (Socket plain = new Socket("127.0.0.1", port)) {
                plain.getOutputStream().write(new byte[64]);
            }
            client.send(frame);
            require(
                    received.get() == 27,
                    "plaintext attempt does not displace authenticated connection");
            corruptAck.set(true);
            try {
                client.send(frame);
                throw new AssertionError("Invalid acknowledgement accepted");
            } catch (IOException expected) {
                require(expected.getMessage().equals("Invalid handoff acknowledgement"), "invalid ACK rejected");
            }
            require(!client.connected(), "invalid ACK closes compromised session");
            await(client::connected);
            client.send(frame);
            require(received.get() == 29, "reconnect after invalid ACK restores transfers");
        } finally {
            server.close();
        }
        testFrameDeadlines(keys, port, secret, handler, log);
        System.out.println(
                "PASS: "
                        + checks
                        + " TLS authentication, duplex concurrency, disconnect, reconnect and"
                        + " heartbeat checks");
    }

    static SSLSocket rawPeer(Path keys, int port) throws Exception {
        SSLSocket socket = (SSLSocket) BridgeTls.context(keys.resolve("thunion"))
                .getSocketFactory().createSocket("127.0.0.1", port);
        socket.setSoTimeout(3000);
        socket.startHandshake();
        DataOutputStream out = new DataOutputStream(socket.getOutputStream());
        out.writeInt(0x54424c33);
        out.writeUTF("thunion");
        out.writeUTF("pkumc");
        out.flush();
        DataInputStream in = new DataInputStream(socket.getInputStream());
        require(in.readInt() == 0x54424c33 && in.readUTF().equals("pkumc")
                && in.readUTF().equals("thunion"), "raw peer identity exchange");
        return socket;
    }

    static void testFrameDeadlines(Path keys, int port, byte[] secret,
            BridgeLink.Receiver handler, org.slf4j.Logger log) throws Exception {
        try (BridgeLink server = new BridgeLink(config(keys.resolve("pkumc"), true, port, secret), handler, log)) {
            server.start();
            try (SSLSocket peer = rawPeer(keys, port)) {
                await(server::connected);
                DataOutputStream out = new DataOutputStream(peer.getOutputStream());
                out.writeByte(2);
                out.writeLong(-1);
                out.writeInt(32);
                out.flush();
                // No body follows: invalid headers must be rejected without waiting for it.
                long end = System.nanoTime() + TimeUnit.SECONDS.toNanos(1);
                while (server.connected() && System.nanoTime() < end) Thread.sleep(10);
                require(!server.connected(), "invalid ACK header rejected before body read");
            }
            try (SSLSocket peer = rawPeer(keys, port)) {
                await(server::connected);
                OutputStream out = peer.getOutputStream();
                out.write(3);
                out.flush();
                for (int i = 0; i < 10 && server.connected(); i++) {
                    Thread.sleep(250);
                    try {
                        out.write(0);
                        out.flush();
                    } catch (IOException closed) {
                        break;
                    }
                }
                require(!server.connected(), "trickled frame cannot extend total read deadline");
            }
        }
    }
}
